name: get_cli
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  image_picker: ^1.0.2
  image_cropper: ^4.0.1
  image_crop: ^0.4.1
  flutter_image_compress: ^2.0.4
  local_auth: ^1.1.0
  speech_to_text: ^6.1.1
  avatar_glow: ^2.0.2
  signature: ^5.4.0
  flutter_colorpicker: ^1.0.3
  permission_handler: ^10.4.3
  image_gallery_saver: ^2.0.3



dev_dependencies: 
  flutter_lints: 2.0.2
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

